# Generated by Django 2.2.16 on 2021-07-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
